/*
  # Add PDF Reports Storage System

  ## Overview
  This migration adds Supabase Storage integration for storing PDF reports generated by users.

  ## 1. Schema Changes

  ### user_files table
  - Add `file_url` column (text) - URL to the file in Supabase Storage
  - Add `storage_path` column (text) - Path in storage bucket for easier management

  ## 2. Storage Setup

  ### Create 'reports' bucket
  - Public bucket for easy access to report PDFs
  - Files organized by user_id and timestamp

  ### Storage Policies
  - Admins can read all reports
  - Users can read their own reports
  - Authenticated users can upload reports
  - File path structure: /reports/{user_id}/{timestamp}_report.pdf

  ## 3. Security
  - RLS policies control access to file records in database
  - Storage policies control access to actual files
  - Users can only access their own reports unless they're admin
*/

-- Add file_url and storage_path columns to user_files table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_files' AND column_name = 'file_url'
  ) THEN
    ALTER TABLE user_files ADD COLUMN file_url text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_files' AND column_name = 'storage_path'
  ) THEN
    ALTER TABLE user_files ADD COLUMN storage_path text;
  END IF;
END $$;

-- Create storage bucket for reports
INSERT INTO storage.buckets (id, name, public)
VALUES ('reports', 'reports', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing policies if they exist (idempotent migration)
DO $$
BEGIN
  DROP POLICY IF EXISTS "Admins can read all reports" ON storage.objects;
  DROP POLICY IF EXISTS "Users can read own reports" ON storage.objects;
  DROP POLICY IF EXISTS "Users can upload reports" ON storage.objects;
  DROP POLICY IF EXISTS "Users can delete own reports" ON storage.objects;
  DROP POLICY IF EXISTS "Admins can delete any report" ON storage.objects;
END $$;

-- Storage Policy: Admins can read all reports
CREATE POLICY "Admins can read all reports"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'reports' AND
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role = 'admin'
    )
  );

-- Storage Policy: Users can read their own reports
CREATE POLICY "Users can read own reports"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'reports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Storage Policy: Authenticated users can upload reports
CREATE POLICY "Users can upload reports"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'reports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Storage Policy: Users can delete their own reports
CREATE POLICY "Users can delete own reports"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'reports' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

-- Storage Policy: Admins can delete any report
CREATE POLICY "Admins can delete any report"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'reports' AND
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
      AND user_profiles.role = 'admin'
    )
  );

-- Create index on file_url for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_files_file_url ON user_files(file_url);
CREATE INDEX IF NOT EXISTS idx_user_files_storage_path ON user_files(storage_path);

-- Add comment to document the file_url column
COMMENT ON COLUMN user_files.file_url IS 'Public URL to access the file in Supabase Storage';
COMMENT ON COLUMN user_files.storage_path IS 'Path in storage bucket: reports/{user_id}/{timestamp}_report.pdf';